### ISSUE TITLE
[bug]: APA partition is broken; aborting

### ISSUE THREAD

**Issue by orcutt989** [israpps/HDL-Batch-installer#15]
### Issue

I'm using a HDD I just formatted in uLaunchELF 2TB. I plugged it into my PC and when I click "search ps2 HDD's" the CMD window says ERROR APA Partition is broken, aborting, and a window pops up that says "wxWidgets Debug alert" and wants to abort the program.

### expected behaviour

I was hoping for HDL Batch Installer to recognize my drive without error.

### Program version

3.1.1 Beta 64 Bits

### other checks

- [X] I am using the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Hi!

It seems to be a problem related to the hard drive format

Please, format again with [wLaunchELF 4.43x_isr](https://github.com/israpps/wLaunchELF_ISR/releases/download/latest/BOOT.ELF) And try again

**Comment by orcutt989** [comment]
Turns out I had a bad drive and I wasn't creating the +OPL partition. I created it manually on a different drive and presto your program works - Apologies!

**Comment by israpps** [comment]
Well, I'm glad it was something "fixable".
I hope you enjoy this software.

Have fun!
