### ISSUE TITLE
[bug]: Cannot transfer Soulcalibur 3 to my PS2 HDD

### ISSUE THREAD

**Issue by pftmclub** [israpps/HDL-Batch-installer#21]
### Issue

the problem was my soul calibur 3 get error when transfer to PS2 HDD. Nothing is work whenever Database is using or not

![image](https://user-images.githubusercontent.com/19551146/145413012-6fcbc6df-3559-4c18-a86f-145993c180e4.png)

### expected behaviour

I expected...

### Program version

version 3.1.3 rev1

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
It seems that `\` characters are being interpreted as chinese simbols, as you can see in the console log...

The presence of such simbols on the game path indicates an issue on the file search dialog call....

**Comment by israpps** [comment]
now that i inspect the image closely....

I can see the same problem on the hdl dump message...

something else is going on

**Comment by israpps** [comment]
try installing the game again...

But this time.... launch the program from a command line console passing this command:
```
HDL-Batch-installer.exe --force-max-debug --redirect-text
```

after installing the game (wich should also fail)
Compress the `logs` folder created on program location into a zip archive and send it to me.

I want to take a look at something...

**Comment by pftmclub** [comment]
> 

Thank, btw there is a big problem with HDL batch installer : It's Game name became the same as file names, meanwhile HDL Batch v1.1 only using the name after SLUS/SLPS Game ID

**Comment by israpps** [comment]
> > 
> 
> Thank, btw there is a big problem with HDL batch installer : It's Game name became the same as file names, meanwhile HDL Batch v1.1 only using the name after SLUS/SLPS Game ID

What do you mean?

**Comment by israpps** [comment]
Tested it with a fresh iso from a nice website that has disc images with original hashed (the one that ends on __Paradise__)

![Captura de pantalla (4)](https://user-images.githubusercontent.com/57065102/147394245-2798899e-d2e4-46ba-886c-9aec5cf19dfa.png)
