### ISSUE TITLE
[bug]: Cannot install Silent Hill II unless starting HDL Batch Installer from Command Prompt

### ISSUE THREAD

**Issue by KashtPR** [israpps/HDL-Batch-installer#25]
### Issue

No matter how many times I try to install Silent Hill II (and a bunch of other games), when I start the HDL Batch Installer by going to the install folder, right clicking the HDL-Batch-installer.exe and selecting Run as Administrator, the installer spits out an error and does not install the game.

Please look at the attached image:

![silenthill2](https://user-images.githubusercontent.com/98623002/151665891-28c6f8eb-cb40-4bf4-9a5c-7a2c1dfde4f1.PNG)
 
Very interestingly, if I start the HDL Batch Installer through the command prompt, the game installs without any problem. 

Steps to reproduce:

1. Go to your HDLBInst installation folder
2. Right click on HDL-Batch-installer.exe
3. Select "Run as Administrator"
4. Click "Search ps2 HDD's
5. Click "Search Games"
6. Select "Silent Hil II" iso
7. Click "Install"

This same problem happened to me with about 30 other games. The only way I could get them installed was if I started HDL Batch Installer from the Command Prompt.

Thanks.

### expected behaviour

The game should have been installed properly without any errors.

### Program version

version 3.2.1 [Beta]-[64 bits] Revision: 1 build date: 07-01-2022

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Hi!

Very odd issue...

By launching from command prompt you mean using a CMD.exe instance or the batch file bundled in the package??

**Comment by israpps** [comment]
Also, try to open the app without admin privileges, as the application requests them automatically thanks to an embedded manifest

**Comment by KashtPR** [comment]
> Hi!
> 
> Very odd issue...
> 
> By launching from command prompt you mean using a CMD.exe instance or the batch file bundled in the package??

Yes, when I say Command Prompt it means that I typed CMD in the Windows Search Bar, right clicked it, and ran it as administrator. 



> Also, try to open the app without admin privileges, as the application requests them automatically thanks to an embedded manifest

Already tried this as well, it did not work. I have a list of about 30 games that have this same issue, so it is not isolated to this one particular game, it just happened to be the first one I saw the error on.

**Comment by KashtPR** [comment]
Here is a quick video reproducing the issue: https://youtu.be/hl1ffwH1ZCE

**Comment by israpps** [comment]
> Here is a quick video reproducing the issue: https://youtu.be/hl1ffwH1ZCE

this is very odd......

There is no error code 100 on HDLDump....

could you test if the same happens while loading the program via the .bat file located in the package???

**Comment by KashtPR** [comment]
> this is very odd......
> 
> There is no error code 100 on HDLDump....
> 
> could you test if the same happens while loading the program via the .bat file located in the package???

Tried with the .BAT file in the package and same error. So going to the actual package folder and double clicking either the .exe or the .bat file will result in the error. It will install perfectly fine if I open CMD then manually type HDL-Batch-installer.exe like I did in the video. It is the only way that installing those specific games work.

**Comment by israpps** [comment]
@KashtPR could you reproduce the error but this time redirecting output to the text files.

This will help me out to troubleshoot

**Comment by israpps** [comment]
@KashtPR Please test this package
https://github.com/israpps/HDL-Batch-installer/suites/5395030346/artifacts/169969566
