### ISSUE TITLE
My patched game was rejected by the program

### ISSUE THREAD

**Issue by InCah00ts** [israpps/HDL-Batch-installer#27]
### Issue

Version: 3.3.0
Game: Initial D Special Stage 1.1/1.2

What happens: Installing unpatched ISO injects ISO no issue. After patching ISO via xdelta HDL kicks back error that ISO is not PS2 ISO, no other error message.

Patched 3 different Initial D ISOs to rule out bad ISO

Author of patch notes that patch ISO can be run on original PS2 hardware. Via author's discord, this should be no issue running patched ISO on original hardware.

### expected behaviour

Inject ISO without fault? Not sure what to submit here.

### Program version

3.3.0

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
It seems that this xdelta patch is making the ISO a non playstation compliant disc image.

Please... Check the log to see the reason

If it is a non playstation ISO, modify the iso with ultraiso by making sure the image has the assigned size for the type of image and the UDF checkbox marked

**Comment by israpps** [comment]
I made a PR to HDLDump that could possibly fix this...
https://github.com/ps2homebrew/hdl-dump/pull/58
