### ISSUE TITLE
[bug]: Doesn't detect PS2 HDD if there are a lot of drives in the system

### ISSUE THREAD

**Issue by haegrr** [israpps/HDL-Batch-installer#28]
### Issue

I have about 20 drives (physical and virtual) in my system and HDL Batch Installer won't recognize my PS2 drive (currently drive number 20). I've encountered the same issue with HDL Dumb (which has a [hardcoded limit of 16 drives](https://github.com/ps2homebrew/hdl-dump/blob/9f071d78dd033aba7eb0eb71b247ee9b02e2a901/osal_win32.c#L386)), HDLBATCH and OPL Manager.

### expected behaviour

Expected behavior: my PS2 HDD is found.

### Program version

3.3.0 revision 1

### other checks

- [x] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Hi!

This is an HDLDump issue, not directly related to my GUI.

I'll take a look at this in a few days...

However, if you want to speed up things a bit, please [open a issue on HDLDump ](https://github.com/ps2homebrew/hdl-dump/issues)

**Comment by israpps** [comment]
After a quick inspection it seems that HDLDump only iterates on the first 16 drives...

I already asked the project maintainer if such limit can be increased

**Comment by israpps** [comment]
Already Opened a Pull Request on hdl-dump...

The maintainer said he isn´t aware of any issue....

Actually, hdl-dump of ancient times was limited to only 4 drives AFAIK

**Comment by israpps** [comment]
Fixed on HdlDump mainstream

Merged to my own repo...

Update on your HDL Batch installer package with the HdlDump update feature

Or re-download package

**Comment by haegrr** [comment]
Thanks for this @israpps. I can confirm that the drive (currently numbered 18) is now detected and I'm instead seeing the error associated with #29.

**Comment by israpps** [comment]
> Thanks for this @israpps. I can confirm that the drive (currently numbered 18) is now detected and I'm instead seeing the error associated with #29.

yeah, yesterday while i was drunk i fixed the issue...

I might release a fix today
