### ISSUE TITLE
[hdl-dump issue]: `input or output is unsupported` on HDD hdl toc request

### ISSUE THREAD

**Issue by Metal42Monkey** [israpps/HDL-Batch-installer#29]
### Issue

the problem seems to be with WGET, I have tried loading everything as admin and also moved the files to the non boot HDD to make sure, I will attach a picture of the error message:
<img width="308" alt="Desktop Screenshot 2022 03 31 - 05 00 28 17" src="https://user-images.githubusercontent.com/102691049/160904404-cbc719ac-b734-4d1e-b74c-79cbe837b416.png">

I can choose to not quit the program but nothing from there seems to work, HDD isn't accessible etc. The HDD was formatted with WINHIIP and had some games on it installed from there, I deleted all of them just in case one was causing the overflow error. Now it only has FHDB etc and a couple of virtual memory cards.

### expected behaviour

I expected... HDD to be accessible as per the instructions.

Any help would be greatly appreciated as I have heard WINHIIP is bad and I should be using this, but so far I can't seem to get it to recognize my HDD.

### Program version

3.3.0 rev 1

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by Metal42Monkey** [comment]
Sorry, forgot to mention, the error happens when I search for ps2 HDD's. It will find my drive (11 and it's the last one, so not an over 16 error) but then this error and nothing working from there.
The drive is plugged into a USB3 dock which has been working fine for WINHIIP so far.

**Comment by israpps** [comment]
Check inside the console log to see which error was reported

If HDLDump reported APA partition broken it can mean two things:

1. What the message actually says
2. The hard drive isn't properly connected

**Comment by Metal42Monkey** [comment]
If by the console log you mean the non GUI screen (sorry not sure if you meant a log file but I can't seem to find a log folder so I assume that is what you meant)
```console
Game Title Database, 15156 ID's registered
        hdd0: 228934 MB
        hdd1: 457860 MB
        hdd2: 476937 MB
        hdd3: 476937 MB
        hdd4: 457860 MB
        hdd5: 953867 MB
        hdd6: 1907726 MB
        hdd7: 476937 MB
        hdd8: The device is not ready.
        hdd9: The device is not ready.
        hdd10: The device is not ready.
        hdd11: 457860 MB, formatted Playstation 2 HDD
selected hdd11
ERROR ---
Input or output is unsupported.
```
This is the exact text copy pasted if that helps?

**Comment by Metal42Monkey** [comment]
sorry that posted huge, also the HDD should be inserted correctly, I got into WINHIIP and found it no problems to delete the game ISO's in case that was the problem. Sadly it didn't help

**Comment by Metal42Monkey** [comment]
It doesn't seem to have reported the partition broken so much as had some kind of I/O error from what I can tell. So far it seems I am the only one to have this error (typical lol) so a google hasn't helped me. Hoping you might be able to shed some light on it and possibly help someone else in future if I can figure it out. Thanks.

**Comment by israpps** [comment]
Lol

This is new..

I never saw the error message input or output is unsupported while trying to read HDD...

Wich software was used to format the drive?

**Comment by Metal42Monkey** [comment]
I did the instructions to install FHDB from https://www.ps2-home.com/forum/viewtopic.php?f=69&t=4625

I believe I used HDDRAWCOPY to put the FHDB image direct to the HDD, I had to use an older version to make it compatible with my 3rd party adapter but I got it working with WINHIIP without too many issues, except some games not loading with a VMC set up which someone said might be a WINHIIP problem and recommended that I try this instead.
Unfortunately I seem to have found a bug!

**Comment by Metal42Monkey** [comment]
What would you recommend to format the drive for PS2? I have a VMC with a couple of saves on the drive but if needed I'll just wipe it all and start again.

**Comment by Metal42Monkey** [comment]
Actually thinking about it, I may have used WINHIIP's "format drive" option in the end when the rawcopy wasn't working as expected.

**Comment by Metal42Monkey** [comment]
and it's a 500gb SSD if that makes a difference

**Comment by israpps** [comment]
You used premade image

That is the issue

**Comment by israpps** [comment]
https://israpps.github.io/FreeMcBoot-Installer/test/FHDB-TUTO.html

**Comment by Metal42Monkey** [comment]
That helps greatly, I was beginning to wonder since most forums say install FHDB from a USB etc and format from there.
Trouble is, I am using a fixer PS2 that I managed to get working but the USB drives are rusty and I have to give it a good detail to get them working again, which is why I went the image route.
Thanks, I'll close this off. Hopefully it helps someone else who did their HDD the same way as I did. I'll see if I can back up the saves from the VMC's to a meat memory card in the real world and just format the drive again. I think I grabbed my FMCB card from my friend's place so I'll see if I can just use that. Thanks.

**Comment by Metal42Monkey** [comment]
Sorry had to re-open this one, I just sanded out my USB ports and the drive now works, put the installer on there and formatted the HDD in the PS2 this time following the guide, made the partition etc. All done with no errors as with the guide.
Same error when I try to use HDL batch though. Looks like the formatting on the HDD wasn't the issue!
I give up for the night after all of that, but I'll check in after work tomorrow and see if there are any new ideas. Thanks in advance.

**Comment by Metal42Monkey** [comment]
Update because I didn't quite give up and tried a few more things, specifically I blanked the drive again, formatted it again with the PS2 and the installer on USB, confirmed it was all working fine on the PS2 by re-booting with the FMCB card and the USB removed, booted up to the HDD no issues.
I now have a fresh problem, I tried again with HDL and got same error, problem is, I then figured I would try to format with WINHIIP again since that worked before, opened that up and suddenly it thinks the partition I made with the USB and FMCB was faulty and wanted to fix it, when I tried to let it, it said it couldn't write to the disk! I then tried to re-format the whole thing with HIIP but now nothing will write to the disk at all!
I seem to have installed a working copy of FHDB and also somehow made my drive inaccessible to my computer in any way! I'll have to try blanking it again tomorrow. For now I need to pass out and get up for work.
Before I did the FMCB/USB install I could read/write in WINHIIP no issues, I even deleted all of the ROMS with it when the first error came up in HDL!
I'm absolutely stumped now and it seems my problems are only getting worse the more I try to fix them. I hope I didn't kill a new 500gb SSD! Though it seemed to work just fine with the format in the ps2 just now. I have no idea why it suddenly won't read/write in any programs now. Sigh. Trust me to find the 1 in a million bug that breaks everything...

**Comment by Metal42Monkey** [comment]
Picard facepalm... Checked disk manager and the drive was offline... works in winhiip again now but still the same error in HDL no matter what I have tried. Doesn't matter how I do the image on the disk, I get the exact same error.

**Comment by israpps** [comment]
This is very odd...

Please, run some HDD checking program.

Such as:

Crystal disc on PC

Or HDDChecker on the ps2 itself

**Comment by Metal42Monkey** [comment]
I just plugged in to the dock and ran crystal disk before work, as expected (it's a brand new out of the pack drive) It says the drive is 100% good. I'm still stumped unfortunately.

**Comment by Metal42Monkey** [comment]
I'll try running HDDChecker on the ps2 itself after work and let you know if that found anything. The format and everything on the PS2 went through without a hitch though. As far as I can tell the drive works perfectly apart from in HDL. TBC in about 8 or 9 hours when I get back from work. Thanks for still trying.

**Comment by Metal42Monkey** [comment]
Just before I start, the drive is a gigabyte 480GB ssd. I don't know if that makes a difference. I might grab a cheap 240 off Amazon and try that just in case something about this drive is causing the issue. Been meaning to use it for my PC and get something a bit smaller for the PS2 anyway.

**Comment by haegrr** [comment]
This could possibly be an issue with having many drives in your system. I'm encountering the same issue (I was also encountering #28 when my drive got numbered beyond the 16 drive limit, but worked around it by rebooting my machine to get it below 16).

I've encountered this error before in OPL manager: https://www.ps2-home.com/forum/viewtopic.php?t=10404 and there it had to do with the trailing colon getting cut off for drive numbers in the double digits. `hdl_dump` requires this colon to be present.

```
PS Q:\> hdl_dump hdl_toc hdd11
Input or output is unsupported.

PS Q:\> hdl_dump hdl_toc hdd11:
type     size flags           dma startup      name
total 1907712MB, used 4096MB, available 1903616MB
```

A possible workaround is to keep rebooting your computer until Windows enumerates your PS2 drive as 0-9 (pulling drives if needed).

**EDIT:** can confirm that it works when harddrive is hdd9!

**Comment by israpps** [comment]
Hmmm, I'll fix this on next release

**Comment by Metal42Monkey** [comment]
Hi, sorry for the late reply, I have been off work sick.
I just tested again and my drive came up as drive 7 in the manager, I also updated to your latest version, I'm not sure which has fixed it, but it appears to be working fine now! Thank you I'll stop using winhiip now!
