### ISSUE TITLE
[FR]: ZSO Support

### ISSUE THREAD

**Issue by orcutt989** [israpps/HDL-Batch-installer#30]
### Explanation

https://github.com/ps2homebrew/Open-PS2-Loader/issues/225#issuecomment-112133647

OPL now has ZSO support so it would be great to use HDL Batch installer to load these on the drive. Right now its only possible to load these files via FAT32-formatted USB.

### fature related

- [ ] game Installation
- [ ] Title Database
- [ ] ART Downloader
- [X] Game management
- [X] HDD management
- [ ] Others...

### other checks

- [ ] I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
- [ ] This Feature requires an update of WxWidgets

**Comment by israpps** [comment]
Hi!

OPL Has no support yet...

as you can see in the [ZSO feature pull request](https://github.com/ps2homebrew/Open-PS2-Loader/pull/641) it´s still marked as draft.

It will take some time...

Performance in certain devices is still shitty.
And RAM Usage must be adjusted...

also, [ZSO support](https://github.com/AKuHAK/hdl-dump/commit/af155961ea315fb217d799844f93f6753061b8e3) has not reached upstream HDLDum, I will wait for that before adding support to my program.

**Comment by orcutt989** [comment]
Hey! So @JoseAaronLopezGarcia actually has a build in the issue https://github.com/JoseAaronLopezGarcia/Open-PS2-Loader-ZSO/releases/tag/r111

**Comment by israpps** [comment]
> Hey! So @JoseAaronLopezGarcia actually has a build in the issue https://github.com/JoseAaronLopezGarcia/Open-PS2-Loader-ZSO/releases/tag/r111

I know

I'll wait until upstream HdlDump has support for these images

**Comment by israpps** [comment]
Coming soon!

https://github.com/ps2homebrew/hdl-dump/pull/57

**Comment by orcutt989** [comment]
Awesome thanks so much!!

**Comment by israpps** [comment]
Added front -end support...
Awaiting for HDL dump support

**Comment by orcutt989** [comment]
Its merged @israpps

**Comment by orcutt989** [comment]
I tried dropping in the new hdl-dump EXE, but I get a bad ISOFS when trying to import.  I suppose there might be more work to do.

**Comment by israpps** [comment]
@GDX-X let me guess, cdvd_info commands don't work on zso right?

**Comment by GDX-X** [comment]
No they don't work. to get the gameid I use `grep -o -m 1 "[A-Z][A-Z][A-Z][A-Z][_][0-9][0-9][0-9].[0-9][0-9]" | head -1`
https://github.com/GDX-X/PFS-BatchKit-Manager/blob/main/PFS-BatchKit-Manager/!PFS-BatchKit-Manager.bat#L1061

**Comment by israpps** [comment]
yeah, i'm not adding grep lol

And traversing the file blindly is kinda stupid...

Maybe @AKuHAK has some idea of how to implement it on hdl-dump

**Comment by GDX-X** [comment]
it does not go through the file blindly, it searches for the specific gameid moreover, it finds the gameid in milliseconds because the gameid is at the beginning of each file and the head -1 command is used to exit the search process.

this is a solution that works fine, I assume a similar command must exist in c+

**Comment by israpps** [comment]
> it does not go through the file blindly, it searches for the specific gameid moreover, it finds the gameid in milliseconds because the gameid is at the beginning of each file and the head -1 command is used to exit the search process.
> 
> this is a solution that works fine, I assume a similar command must exist in c+

for doing a C++ program, i would need a search range (like POPS VCD ID extractor has)

or search in a stream reading system

**Comment by orcutt989** [comment]
Helpful @israpps ? Any of these comments?
https://stackoverflow.com/a/5731118

**Comment by israpps** [comment]
Please try latest package again...

**Comment by orcutt989** [comment]
Seems great. Any way to inject icons into already loaded games? While we were waiting I used this to transfer all my zsos https://github.com/GDX-X/PFS-BatchKit-Manager @israpps

**Comment by israpps** [comment]
There is a feature for that

Check the installed game list options (right click)

**Comment by israpps** [comment]
ZSO support recieved a non minor change that you won't be happy with.

Take a look at it

**Comment by orcutt989** [comment]
> ZSO support recieved a non minor change that you won't be happy with.
> 
> 
> 
> Take a look at it

Where? Hdl dump?

**Comment by israpps** [comment]
Yup

**Comment by orcutt989** [comment]
.https://github.com/ps2homebrew/hdl-dump/pull/61 yeah this sucks. What could be the benefit of needing duplicate files?

**Comment by israpps** [comment]
i think this can be closed

**Comment by orcutt989** [comment]
Thanks for everything!
