### ISSUE TITLE
[FR]: Support for BIN files

### ISSUE THREAD

**Issue by orcutt989** [israpps/HDL-Batch-installer#31]
### Explanation

It would be nice to have support from BIN files.

### fature related

- [ ] game Installation
- [ ] Title Database
- [ ] ART Downloader
- [X] Game management
- [X] HDD management
- [ ] Others...

### other checks

- [ ] I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
- [ ] This Feature requires an update of WxWidgets

**Comment by israpps** [comment]
Support for CD `.BIN` files is already implemented

The program asks for the `.CUE` File instead, but it will install the bin file
