### ISSUE TITLE
[bug]: Warning, missing split token at external database line [4685], skipping entry...

### ISSUE THREAD

**Issue by matcarfer** [israpps/HDL-Batch-installer#34]
### Issue

using external database, this **WARNING** shows:
![image](https://user-images.githubusercontent.com/15199805/188531254-f604b359-9d01-4996-8bec-d9f2e3d3a108.png)

### expected behaviour

I expected...

### other checks

- [x] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Your external database is missing a semicolon on line `4685`

That semicolon splits the ELF ID from the gamename

Sample:
```
SLPM_666.75;Kingdom Hearts 2 - Final Mix+
```

**Comment by israpps** [comment]
Please let me know if a semicolon is actually missing, if not, then this issue is valid, otherwise, it's not a program issue

**Comment by matcarfer** [comment]
> Please let me know if a semicolon is actually missing, if not, then this issue is valid, otherwise, it's not a program issue

You are right, thing is, the database was downloaded with HDL-Batch-installer

**Comment by matcarfer** [comment]
I added it manually and warning is gone.
"SLED_518.32 Sphinx and the Cursed Mummy" to ""SLED_518.32;Sphinx and the Cursed Mummy""

**Comment by israpps** [comment]
> I added it manually and warning is gone. "SLED_518.32 Sphinx and the Cursed Mummy" to ""SLED_518.32;Sphinx and the Cursed Mummy""

Great!
