### ISSUE TITLE
[bug]: Failed Installation: -1073741819l

### ISSUE THREAD

**Issue by TristanTheBeep** [israpps/HDL-Batch-installer#35]
### Issue

Getting Failed installation on all ISOs to a newly formatted drive (Formatted with uLaunchELF)

Console output during install:

> index: 61
> DVD 1305152KB "HOMINID" "SLUS_210.90"
> media: inject_dvd
> searching [SLUS_210.90]
> $ found match! [Alien Homind]
> Searching custom icon: No custom icon found
> 
> inject_mode: [inject_dvd ]
> hdd_target: [hdd4:]
> title: [Alien Homind]
> ISO_PATH: [D:\PS2\Alien Hominid.iso]
> ELF [SLUS_210.90]
> DMA: *u4
> Hide_switch:
> 
> 
> HDL.EXE inject_dvd  hdd4: "Alien Homind" "D:\PS2\Alien Hominid.iso" SLUS_210.90 *u4
> 100%, 1 sec remaining, 32.25 MB/sec
> returned value [-1073741819]
> Elapsed time 31958(ms)

  
Console output post install:

> 
> installation process finished.
> Failed installation summary:
> #61
> D:\PS2\Alien Hominid.iso
> SLUS_210.90
> -1073741819l
> 
> 

The number is 61 as this happened on all 63 games I attempted to install. Checking the games list on the drive with HDL loader however shows that they have been installed. 

### Program version

version 3.4.0 [Release Candidate]-[-[64 bits]]

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Hi!

It seems it's an error on the UI handling the return code

It seems the games are properly installed, but return code should be 0 (or it's 0 and somehow another value gets there?)

**Comment by TristanTheBeep** [comment]
Yeah based on your response on the discord to the other person with the issue I figured that too. I wanted to share more info for you though and I didn't want to clutter the discord haha

**Comment by israpps** [comment]
Thank you for reporting!
