### ISSUE TITLE
[bug]: Game installations result in returning a value of -1073741819 99% of the time.

### ISSUE THREAD

**Issue by ItalianGamer97** [israpps/HDL-Batch-installer#37]
### Issue

For a majority of the PS2 games I attempted to install onto my 1TB Seagate Black SATA HDD, the program returned a value of -1073741819 for a majority of my installations across both the x64 and the x86 versions. This would result in the installations seemingly failing, and yet the games would be there on refreshing the list of installed games.

On the PS2 side, the games would also be visible in OPL when the HDD is plugged up into my system, but I noticed that two of the games I had recently installed, namely Jimmy Neutron Boy Genius: Attack of the Twonkies and God Of War II have had major game-halting issues, with the former freezing in the middle of the opening cutscene while the latter gets stuck on a black screen after its own opening cutscene.

Below are copies of the command-prompt logs I've copy-pasted into text files for your convenience.

[Log for HDL Batch Installer 3.4.0 Release Candidate 32-bit bug - Returning giant negative value for all selected PS2 games during batch installation.txt](https://github.com/israpps/HDL-Batch-installer/files/9843437/Log.for.HDL.Batch.Installer.3.4.0.Release.Candidate.32-bit.bug.-.Returning.giant.negative.value.for.all.selected.PS2.games.during.batch.installation.txt)
[Log for HDL Batch Installer 3.4.0 Release Candidate 64-bit bug - Returning giant negative value for 103 out of 104 of my PS2 games during batch installation.txt](https://github.com/israpps/HDL-Batch-installer/files/9843438/Log.for.HDL.Batch.Installer.3.4.0.Release.Candidate.64-bit.bug.-.Returning.giant.negative.value.for.103.out.of.104.of.my.PS2.games.during.batch.installation.txt)

### expected behaviour

I expected for all of the game installations to _not_ return the value of -1073741819 on completion.

### Program version

3.4.0 Release Candidate (32-Bit and 64-Bit)

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Thanks for reporting

This will be fixed soon

I already found the culprit.

I just didn't have time to finish some coding not related to this issue

Then I'll push an update

**Comment by israpps** [comment]
please check latest version

**Comment by ruskiturbo1337** [comment]
I have the same issue described here and the latest versions does not work for me unfortunately :/
Also I get an HDL.EXE app error that reads like this: 'Instruction in 0x0000000000AB2727 referenced memory at 0x0000000000000050 The memory could not be read.'
[Install.log](https://github.com/israpps/HDL-Batch-installer/files/9889449/Install.log)

**Comment by Deinonychus71** [comment]
Hi!
I have the same issue. Tried with x86 and x64 versions. Game seems to work fine.

**Comment by israpps** [comment]
fuck...

Now i'm really lost....

Not sure how, why or what to blame

let's try rebuilding hdl-dump

in 15 minutes, use the HDL Batch Installer option to update HDL Dump and we will if it was a compilation issue, wich i don't believe it is, but won't hurt to try

**Comment by israpps** [comment]
it has been confirmed that this issue was on HDL Dump side.

I have fixed it from both sides, on HDL Dump, zso support was removed temporarly, and on HDL Batch Installer size, the return code `-1073741819` will be considered a successfull installation, so this will be no longer an issue
