### ISSUE TITLE
Issue with Patched ISO

### ISSUE THREAD

**Issue by MythicWebsite** [israpps/HDL-Batch-installer#42]
I've looked all over and have been unable to find anything to solve this issue.

![HDL-Batch-installer_SKOSLyQo4e](https://user-images.githubusercontent.com/78496235/201507483-2b7b4223-9238-4a58-8c13-818b59c0e937.png)

This is an english patched version of .Hack//Fragment using the method from here [https://bbs.dothackers.org/viewtopic.php?f=6&p=262](https://bbs.dothackers.org/viewtopic.php?f=6&p=262)

I've tried looking at the system.cnf, but it's no different than the original ISO. Unsure what to try to get it to work. The unpatched rom works fine.

**Comment by israpps** [comment]
Yeah, it is a known issue

Your rebuilt ISO is missing important information of standard PS2 games

I can add a workaround later

**Comment by israpps** [comment]
this issue should be fixed on latest HDL-Dump, wich has the `PLAYSTATION` magic string check disabled (wich causes the program to reject those poorly made game mods)

I'll let this open till i get confirmation on your side.

But it will work for sure.

**Comment by MythicWebsite** [comment]
Seems to have worked perfect, thank you!
