### ISSUE TITLE
[FR]: Delete game partition

### ISSUE THREAD

**Issue by luongthien93** [israpps/HDL-Batch-installer#46]
### Explanation

Could you add Delete partition game, please? I see Delete feature but seem not working now. 
Hope you update on next release. 
Thanks so much. 
Be careful

### fature related

- [ ] game Installation
- [ ] Title Database
- [ ] ART Downloader
- [ ] Game management
- [X] HDD management
- [ ] Others...

### other checks

- [X] I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
- [X] This Feature requires an update of WxWidgets
- [X] Needs an update of [HDL Dump](https://github.com/ps2homebrew/hdl-dump)

**Comment by israpps** [comment]
> ### Explanation
> Could you add Delete partition game, please? I see Delete feature but seem not working now. Hope you update on next release. Thanks so much. Be careful
> 
> ### fature related
> * [ ]  game Installation
> * [ ]  Title Database
> * [ ]  ART Downloader
> * [ ]  Game management
> * [x]  HDD management
> * [ ]  Others...
> 
> ### other checks
> * [x]  I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
> * [x]  This Feature requires an update of WxWidgets
> * [x]  Needs an update of [HDL Dump](https://github.com/ps2homebrew/hdl-dump)

It's implemented and disabled because it can fuck HDD APA chain

Enable it by yourself by enabling experimental features on config
