### ISSUE TITLE
[bug]: "APA partition broken" message.

### ISSUE THREAD

**Issue by Broncowave3000** [israpps/HDL-Batch-installer#47]
### "Issue APA partition broken" message.

I have no issues installing games in batch after the first time I format the HDD but after that whenever I connect it to the PS2 console and then remove it to plug it back to my PC an error message will appear on the CMD window "hdd2:: APA partition is broken; aborting."  everytime I click on the "Search ps2 HDD's" button.

![APA partition bug](https://user-images.githubusercontent.com/119262685/204161227-49b248b4-da22-47f6-8d64-7bd9aece466c.png)

### expected behaviour

I expected the program to recognize my HDD to install more games after the first batch install.

### Program version

3.4.2

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
the `APA Partition is broken` message arising on HDDs previously recognized as PS2 HDD 99%of the time means that actually the APA chain is broken or HDD is unproperly connected to PC or power supply is deficient.

your HDD has been recognized, the problem comes when the program is attempting to read data, to fill the gauge and load installed game list

**Comment by Broncowave3000** [comment]
> the `APA Partition is broken` message arising on HDDs previously recognized as PS2 HDD 99%of the time means that actually the APA chain is broken or HDD is unproperly connected to PC or power supply is deficient.
> 
> your HDD has been recognized, the problem comes when the program is attempting to read data, to fill the gauge and load installed game list

But why I only get the message after installing games succesfully, using it on my PS2 and then plugging back the HDD to my PC? Whenever I re-format the HDD with HDD Raw Copy now it will recognize my HDD correctly.

**Comment by israpps** [comment]
> > the `APA Partition is broken` message arising on HDDs previously recognized as PS2 HDD 99%of the time means that actually the APA chain is broken or HDD is unproperly connected to PC or power supply is deficient.
> > your HDD has been recognized, the problem comes when the program is attempting to read data, to fill the gauge and load installed game list
> 
> But why I only get the message after installing games succesfully, using it on my PS2 and then plugging back the HDD to my PC? Whenever I re-format the HDD with HDD Raw Copy now it will recognize my HDD correctly.

something done by the homebrew software on the console seemed to do something that fucked the APA chain.

Also, DONT USE PREMADE IMAGES.

Those are crap, and corrupt the APA chain too!

**Comment by INDRAPhilip** [comment]
I use winhiip to fix errors and then I put the Games through the HDL Batch installer.

**Comment by RedNumber1** [comment]
> I use winhiip to fix errors and then I put the Games through the HDL Batch installer.

@INDRAPhilip how did you get winhiip to run? when I try on windows 11 it just quits after the donation prompt.
