### ISSUE TITLE
Error after every game installed

### ISSUE THREAD

**Issue by JasonMaivia** [israpps/HDL-Batch-installer#54]
Whenever I attempt to install a game onto the PS2 hard drive, which is connected to the PC through USB, it'll say 100% done, with 1 second remaining.

![20230203_174101(0)](https://user-images.githubusercontent.com/124415709/216746070-e8315e2f-623c-4532-a69a-31691cb99080.jpg)

  A message immediately pops up stating that hdl_dump stopped working. 
 The only option is "Close program", but HDL Batch Loader will remain open.

![20230203_173956](https://user-images.githubusercontent.com/124415709/216746031-24a743a0-f345-45f6-bb8f-c4da2d23290f.jpg)

This problem makes it difficult to batch install, since everything stops after every game installed, forcing you to always have to repeatedly click "Close program."  This means I can't install games overnight.

When all of the games are done, a window displays games that couldn't be installed. The weird thing is that it will have every game that was added to the batch installation, but when you update the PS2 hard drive games list, all of those failed games will be there too.

![20230203_174623](https://user-images.githubusercontent.com/124415709/216746052-27be6338-e9bf-4b9c-8db8-4b7af880fa37.jpg)

The error code given looks like 255I.
I do not know what that means.  I would like your help, please.

**Comment by israpps** [comment]
Hi!

I can't reproduce this issue. And error code 255 is not an internal value on HdlDump code, therefore, this seems more like an issue on the os or on some API/library/whatever...

Only thing that comes to my mind so far is trying to shorten the path of the game you're installing

**Comment by israpps** [comment]
please check the HDD connection, the adapter quality (in case u use ide/sata to usb) and try disabling windows anti-ransomware features, since those tend to attack hdl-dump for doing raw HDD I/O access

**Comment by JasonMaivia** [comment]
With everything turned off, and even installing I still get this error. I also swapped cables.  I hope it's not my backup hard drive (checkdisk came up with no errors).

Strangely, HDL Dump Helper GUI works without this issue, but you can only add one game at a time, and it doesn't remember the last game installed in a folder.

I will keep testing things.

**Comment by israpps** [comment]
Please test [this hdl_dump](https://www.mediafire.com/file/fb96yce9cbvt91e/hdl_dump.exe/file)

download the file, rename to `HDL.EXE` and use it to replace the one inside hdl_dump.

since I can't reproduce this issue. this will be utterly hard to fix...

I would like more information of your PC setup, how you connected the HDD and so on.

**Comment by qkwyx** [comment]
> Please test [this hdl_dump](https://www.mediafire.com/file/fb96yce9cbvt91e/hdl_dump.exe/file)
> 
> download the file, rename to `HDL.EXE` and use it to replace the one inside hdl_dump.
> 
> since I can't reproduce this issue. this will be utterly hard to fix...
> 
> I would like more information of your PC setup, how you connected the HDD and so on.

Good day. I have the same experience using 3.5.0 - Revision 1 x86/64 tried both with the same error like on the 3rd screenshot but no experience on the 2nd screenshot. I have win10 x64 4GB ram and using SATA 300GB 2.5"hdd connected to usb external hdd usb2.0 BUT with your test hdl_dump got no issues already.

**Comment by israpps** [comment]
> > Please test [this hdl_dump](https://www.mediafire.com/file/fb96yce9cbvt91e/hdl_dump.exe/file)
> > download the file, rename to `HDL.EXE` and use it to replace the one inside hdl_dump.
> > since I can't reproduce this issue. this will be utterly hard to fix...
> > I would like more information of your PC setup, how you connected the HDD and so on.
> 
> Good day. I have the same experience using 3.5.0 - Revision 1 x86/64 tried both with the same error like on the 3rd screenshot but no experience on the 2nd screenshot. I have win10 x64 4GB ram and using SATA 300GB 2.5"hdd connected to usb external hdd usb2.0 BUT with your test hdl_dump got no issues already.

Mmm

The changes on that test build are already present on the HDL dump distributed with latest HDL batch installer....
