### ISSUE TITLE
[FR]: ZSO Support 

### ISSUE THREAD

**Issue by jbarker2160** [israpps/HDL-Batch-installer#56]
### Issue

ZSO games cannot be installed.

### expected behaviour

To select a ZSO(created by `maxcso`) and have it install to the locally-connected hdd.

### Program version

3.5.0 - r1-x64

### Relevant log output

```shell
type     size flags           dma startup      name
DVD 1592096KB               0 *u4 SLUS_202.65  007 - Agent Under Fire (USA)
total 1907712MB, used 3840MB, available 1903872MB
Loading ISO's------------------------
loaded ISO's: 1
E:\PS2\007 - Everything or Nothing (USA).zso
 Error
        Input or output is unsupported.
```

### In which package have you experienced this issue?

64 bits

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
zso support is temporarily deprecated

Because the zso support breaks installation of DVD9 Games (dual layer)

**Comment by L0g1calMadn3ss** [comment]
Excuse me if I'm wrong, but shouldn't DVD9 games just be converted?
