### ISSUE TITLE
[bug]: Download assets not working

### ISSUE THREAD

**Issue by LeCrabeInfo** [israpps/HDL-Batch-installer#59]
### Issue

The assets are downloaded, but their size is 0 byte.
Then the cleanup script is executed and deletes them because files are empty.

![Capture d'écran 2023-03-06 122929](https://user-images.githubusercontent.com/93468813/223098226-9b0e5b9b-1918-4252-aa75-83d7e7bfc41b.png)

### expected behaviour

Assets downloaded.

### Program version

3.5.0 Revision  1

### Relevant log output

```shell
Downloading...
[SCES_504.91]
SCES_504.91_COV.jpg - 0
SCES_504.91_COV.jpg is empty
SCES_504.91_ICO.png - 0
SCES_504.91_ICO.png is empty
Download finished!
```

### In which package have you experienced this issue?

64 bits

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by LeCrabeInfo** [comment]
The weird thing is that it works via PowerShell:

```
.\common\wget.exe --no-check-certificate --show-progress "https://ia801805.us.archive.org/view_archive.php?archive=/26/items/OPLM_ART_2021_01/OPLM_ART_2021_01.zip&file=PS2%2FSCES_504.91%2FSCES_504.91_COV.jpg" -O .\Downloads\ART\SCES_504.91_COV.jpg

--2023-03-06 12:25:08--  https://ia801805.us.archive.org/view_archive.php?archive=/26/items/OPLM_ART_2021_01/OPLM_ART_2021_01.zip&file=PS2%2FSCES_504.91%2FSCES_504.91_COV.jpg
Resolving ia801805.us.archive.org (ia801805.us.archive.org)... 207.241.230.175
Connecting to ia801805.us.archive.org (ia801805.us.archive.org)|207.241.230.175|:443... connected.
WARNING: cannot verify ia801805.us.archive.org's certificate, issued by 'CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=US':
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [image/jpeg]
Saving to: './Downloads/ART/SCES_504.91_COV.jpg'

./Downloads/ART/SCES_504.91_C     [ <=>                                              ]   8,00K  --.-KB/s    in 0,001s

2023-03-06 12:25:10 (8,96 MB/s) - './Downloads/ART/SCES_504.91_COV.jpg' saved [8194]
```

**Comment by LeCrabeInfo** [comment]
I have disabled Windows Firewall and Windows Defender.
I have deleted HDLBI AppData files, downloaded new archive.
But same problem.

**Comment by israpps** [comment]
Maybe the `--no-check-certificate` is the clue

**Comment by LeCrabeInfo** [comment]
I actually need to add `--no-check-certificate` option because when I don't:

```
.\common\wget.exe --show-progress "https://ia801805.us.archive.org/view_archive.php?archive=/26/items/OPLM_ART_2021_01/OPLM_ART_2021_01.zip&file=PS2%2FSCES_504.91%2FSCES_504.91_COV.jpg" -O .\Downloads\ART\SCES_504.91_COV.jpg

--2023-03-08 10:35:24--  https://ia801805.us.archive.org/view_archive.php?archive=/26/items/OPLM_ART_2021_01/OPLM_ART_2021_01.zip&file=PS2%2FSCES_504.91%2FSCES_504.91_COV.jpg
Resolving ia801805.us.archive.org (ia801805.us.archive.org)... 207.241.230.175
Connecting to ia801805.us.archive.org (ia801805.us.archive.org)|207.241.230.175|:443... connected.
ERROR: cannot verify ia801805.us.archive.org's certificate, issued by 'CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=US':
  Self-signed certificate encountered.
To connect to ia801805.us.archive.org insecurely, use `--no-check-certificate'.
```

What is weird is that I tested on another machine and it works.

**Comment by israpps** [comment]
must be an issue with your certs

**Comment by ironsniper1** [comment]
i am having the exact same issue, went back to version 3.0.3 and it would download assets but they would be 0 bytes in size and not able to be opened, as well if i tried to download assets for more than one game at a time hdl batch crashes

**Comment by israpps** [comment]
let me guess. windows 7?

**Comment by ironsniper1** [comment]
> let me guess. windows 7?

windows 10 latest version, this is also a very fresh install and the laptop is only used for checking hard drives

**Comment by israpps** [comment]
> > let me guess. windows 7?
> 
> windows 10 latest version, this is also a very fresh install and the laptop is only used for checking hard drives

odd indeed. I tested the download feature while coding the current latest update and it worked like a charm...

**Comment by ironsniper1** [comment]
> > > let me guess. windows 7?
> > 
> > 
> > windows 10 latest version, this is also a very fresh install and the laptop is only used for checking hard drives
> 
> odd indeed. I tested the download feature while coding the current latest update and it worked like a charm...

if there is anything you would like me to try let me know

**Comment by ironsniper1** [comment]
<img width="1484" alt="Screenshot 2023-08-05 at 11 28 14 PM" src="https://github.com/israpps/HDL-Batch-installer/assets/39129373/bcfea17d-a746-4c02-ae02-e1dd7aaa2982">
<img width="1483" alt="Screenshot 2023-08-05 at 11 27 28 PM" src="https://github.com/israpps/HDL-Batch-installer/assets/39129373/b93439a4-2eb3-40fa-921d-3e4fe4ed73db">
<img width="1483" alt="Screenshot 2023-08-05 at 11 24 37 PM" src="https://github.com/israpps/HDL-Batch-installer/assets/39129373/953ecdb0-62f8-4c38-a681-e876c7bd336c">

**Comment by israpps** [comment]
you should be getting at least an error there....

**Comment by ironsniper1** [comment]
im not getting any errors

**Comment by israpps** [comment]
open a windows terminal on the HDL Batch installer folder then paste this into the terminal 
```
common\wget.exe https://ia801805.us.archive.org/view_archive.php?archive=/26/items/OPLM_ART_2021_01/OPLM_ART_2021_01.zip&file=PS2%2FSLPM_666.75%2FSLPM_666.75_COV.jpg -O SLPM_666.75_COV.jpg
echo %errorlevel%
PAUSE
```

If it really fails, an error will arise. else it will download kingdom hearts 2 final mix cover art

**Comment by ironsniper1** [comment]
<img width="1060" alt="Screenshot 2023-08-06 at 12 00 02 AM" src="https://github.com/israpps/HDL-Batch-installer/assets/39129373/fac49658-5e50-490b-80be-87dd6c812589">

**Comment by israpps** [comment]
sorry
please prepend an `^` to the ampersand simbol  (,ust look like this`^&`)

```cmd
common\wget.exe https://ia801805.us.archive.org/view_archive.php?archive=/26/items/OPLM_ART_2021_01/OPLM_ART_2021_01.zip^&file=PS2%2FSLPM_666.75%2FSLPM_666.75_COV.jpg -O SLPM_666.75_COV.jpg
echo %errorlevel%
PAUSE
```

**Comment by ironsniper1** [comment]
![error](https://github.com/israpps/HDL-Batch-installer/assets/39129373/729a01b7-0eee-492c-896e-934f2b7bf7ae)

**Comment by israpps** [comment]
ok...

lets try this now:


```cmd
common\wget.exe https://ia802706.us.archive.org/view_archive.php?archive=/4/items/OPLM_ART_2023_07/OPLM_ART_2023_07.zip^&file=PS2%2FSLPM_666.75%2FSLPM_666.75_COV.jpg -O SLPM_666.75_COV.jpg
echo %errorlevel%
PAUSE
```

**Comment by ironsniper1** [comment]
same error, it cannot verify, i did find thishttps://serverfault.com/questions/314635/why-wget-doesnt-verify-ssl-certificates all though its linux it says wget is having an issue with openssl

**Comment by israpps** [comment]
im not an expert on network stuff.... but that error seems like a complain about the website certs...


try this please:
```
common\wget.exe --no-check-certificate https://ia802706.us.archive.org/view_archive.php?archive=/4/items/OPLM_ART_2023_07/OPLM_ART_2023_07.zip^&file=PS2%2FSLPM_666.75%2FSLPM_666.75_COV.jpg -O SLPM_666.75_COV.jpg
echo %errorlevel%
PAUSE
```

**Comment by ironsniper1** [comment]
just tried that before seeing your reply and it works

**Comment by israpps** [comment]
ok... coding a release with the option for this

**Comment by ironsniper1** [comment]
just got a new error, when i tried to open the zip file it couldnt be opened by windows or 7zip

**Comment by ironsniper1** [comment]
![newerror](https://github.com/israpps/HDL-Batch-installer/assets/39129373/427cf6f6-ce6a-41cc-80fb-ac2a700e867d)
![ziperror](https://github.com/israpps/HDL-Batch-installer/assets/39129373/89828870-4ede-4a93-aa57-c9943a9a84f4)

**Comment by israpps** [comment]
you forgot to add `^` before ampersand. without it, windows thinks the text after & is a command to be ran if the text before it runs successfully as a command

**Comment by israpps** [comment]
[HDL-Batch-installer.zip](https://github.com/israpps/HDL-Batch-installer/files/12268759/HDL-Batch-installer.zip)
try this pls

**Comment by ironsniper1** [comment]
works perfectly!

**Comment by Noobsaibot73** [comment]
@israpps  Same issue here: Art files (.bg, .cov, .cov2, .ico, .lgo, .lab, .scr, .scr2) are not being downloaded at all, it seems that a script is missing, no matter if I check (or uncheck) the "no check certificate", it doesn't work.

![Image](https://github.com/user-attachments/assets/6d4750e1-23e2-45e1-9338-6ea2882e3fdb)

Used versions: v3.0.3, v3.4.3, v3.5.1 (Rev. 0), v3.6.0 (Rev. 2), v3.7.0 (Rev. 0. 
V3.0.3 seems to download the art files with no errors, but as this version doesn't let you to mount partitions, you can't check it.
V3.4.3 / V3.5.1 (Rev. 0) Doesn't open the "+OPL" partition but Windows "images" folder (???)
V3.6.0 Usually doesn't download anything, but if you are "lucky", you can get many 0 bytes files.

![Image](https://github.com/user-attachments/assets/0f5f3fe7-e43b-4481-b9fa-665a60d110f6)

![Image](https://github.com/user-attachments/assets/e0deac28-92d3-41a5-b701-b83b5f83c2ee)

Any idea?

**Comment by israpps** [comment]
Seems like the download link is broken...

**Comment by Noobsaibot73** [comment]
> Seems like the download link is broken...

Internally broken? How it could be possible?

**Comment by israpps** [comment]
> > Seems like the download link is broken...
> 
> Internally broken? How it could be possible?

the source where the program pulls images being no longer available for instance...

**Comment by Noobsaibot73** [comment]
> the source where the program pulls images being no longer available for instance...

So v3.7.0 will be the last version?

**Comment by israpps** [comment]
please check if using this one works. add this to a fresh download of 3.7.0.0 and try again

[HDL-Batch-installer.zip](https://github.com/user-attachments/files/19264777/HDL-Batch-installer.zip)

Also, to allow better testing. I've made the following change, that will be merged when this issue is fixed:

Under the config file, a new entry (not exposed to the config UI) will be available, to customize the DL link

```ini

[Artwork]
DataBaseURL=YOUR_CUSTOM_URL_FOR_DOWNLOAD
```

Default internal value is `https://archive.org/download/OPLM_ART_2023_07/OPLM_ART_2023_07.zip/PS2%2F`

This is just a portion of the URL, the program constructs the remaining part on the run based on the requested GameID

**Comment by Noobsaibot73** [comment]
> please check if using this one works. add this to a fresh download of 3.7.0.0 and try again
> 
> [HDL-Batch-installer.zip](https://github.com/user-attachments/files/19264777/HDL-Batch-installer.zip)

Righ now !!!!

**Comment by Noobsaibot73** [comment]
Still displaying those errors... 

![Image](https://github.com/user-attachments/assets/041194e2-65d9-4532-b9b7-871d61c82e15)

But now, seems to be working !!!! 

![Image](https://github.com/user-attachments/assets/f3ad395a-49d3-4b1f-9b1e-67e67aa738b0)

**Comment by israpps** [comment]
> Still displaying those errors...
> 
> ![Image](https://github.com/user-attachments/assets/041194e2-65d9-4532-b9b7-871d61c82e15)
> 
> But now, seems to be working !!!!
> 
> ![Image](https://github.com/user-attachments/assets/f3ad395a-49d3-4b1f-9b1e-67e67aa738b0)

these are not errors.

that script cleanups failed downloads

Bc I cant check if download failed from the download process itself

And downloaded images are not zero sized from the POV of the program. thats why an external script is used

**Comment by israpps** [comment]
I will push the DL fix later.

Then, I will later rewrite the Artwork transfer to use the PFSShell driver instead of depending on DOKAN/PFSFuse

**Comment by Noobsaibot73** [comment]
> I will push the DL fix later.
> 
> Then, I will later rewrite the Artwork transfer to use the PFSShell driver instead of depending on DOKAN/PFSFuse

Ok, thanks a lot !!!!
