### ISSUE TITLE
[FR]: unzip during the process

### ISSUE THREAD

**Issue by GusseDev** [israpps/HDL-Batch-installer#62]
### Explanation

Hello !
A request that may seem a bit silly in this day and age when hard disks are getting cheaper and cheaper, but I was thinking that the possibility of unzipping (*.zip, *.7z) games on the fly would be a great option!
When I see that some games are half their weight when zipped, (Soulcalibur III is 4GB when unzipped, whereas it's only 2.2GB when zipped).
Then maybe there are constraints I haven't considered, and the option is more complex to implement than I think...

congratulations on your great work!

### fature related

- [X] game Installation
- [ ] Title Database
- [ ] ART Downloader
- [ ] Game management
- [ ] HDD management
- [ ] Others...

### other checks

- [X] I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
- [ ] This Feature requires an update of WxWidgets
- [ ] Needs an update of [HDL Dump](https://github.com/ps2homebrew/hdl-dump)

**Comment by Cancelling66** [comment]
You can compress some PS2 ISOs much more than the original using UltraISO. It all depends if the ISO is not completely filled.

**Comment by israpps** [comment]
What you mention sounds like a game with a dummy file

If that game doesn't use Fixed LBAs for finding certain files then identifying and deleting the dummy can help.

**Comment by Cancelling66** [comment]
> What you mention sounds like a game with a dummy file
> 
> If that game doesn't use Fixed LBAs for finding certain files then identifying and deleting the dummy can help.

I was wondering why you don't add an option to delete these dummy files, like UltraISO does. This would avoid using this software every time.

**Comment by israpps** [comment]
> > What you mention sounds like a game with a dummy file
> > If that game doesn't use Fixed LBAs for finding certain files then identifying and deleting the dummy can help.
> 
> I was wondering why you don't add an option to delete these dummy files, like UltraISO does. This would avoid using this software every time.

because it would break some games

**Comment by Cancelling66** [comment]
Weird, I've been doing this on PS2 ISOs for 10 years and I've never had a problem. I have over 300 games installed on the HDD and none have this problem you are talking about.

**Comment by israpps** [comment]
> Weird, I've been doing this on PS2 ISOs for 10 years and I've never had a problem. I have over 300 games installed on the HDD and none have this problem you are talking about.

some games seek data by opening files

other games have hardcoded offsets for files. so if you touch contents the LBA offsets change and game breaks because it assumes certain data to be on certain place on disc

**Comment by Cancelling66** [comment]
In any case, with the UltraISO software, I never had this problem, and all my games work. So I don't know what to tell you about this.

**Comment by israpps** [comment]
still. adding support for zip/7z will make the install process ridiculously slow because I would need to unpack whole zip twice

**Comment by Cancelling66** [comment]
> still. adding support for zip/7z will make the install process ridiculously slow because I would need to unpack whole zip twice

I'm talking about compressing source ISO files, not ZIP or other formats. Some games, like GTA 3, are 4 GB, but UltraISO software can compress them down to 2 GB.

**Comment by israpps** [comment]
> > still. adding support for zip/7z will make the install process ridiculously slow because I would need to unpack whole zip twice
> 
> I'm talking about compressing source ISO files, not ZIP or other formats. Some games, like GTA 3, are 4 GB, but UltraISO software can compress them down to 2 GB.

nearest thing you'll get is ZSO
