### ISSUE TITLE
[bug]: Unspecified error path when installing backups

### ISSUE THREAD

**Issue by fedei91** [israpps/HDL-Batch-installer#66]
### Issue

the problem was
![image](https://github.com/israpps/HDL-Batch-installer/assets/67139533/83468b19-7573-4e53-b9c1-c7c75bdc6ff5)

and the console output was
![image](https://github.com/israpps/HDL-Batch-installer/assets/67139533/0de5d97c-640b-4d81-b986-9a99d81ac9fc)

when specifying a new folder path, without the "é" character, the files can be uploaded / installed
![image](https://github.com/israpps/HDL-Batch-installer/assets/67139533/774a1cb3-38e9-44f3-9147-6a4f91e9890f)

### expected behaviour

I expected the games to be installed.

### Program version

3.5.1 - Revision 1 - x64

### In which package have you experienced this issue?

32 bits, 64 bits

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Should be fixed on newer releases
