### ISSUE TITLE
[bug]: Save button in settings does nothing

### ISSUE THREAD

**Issue by Haker120** [israpps/HDL-Batch-installer#7]
### Issue

None of settings are saved by GUI, they do, however, work when manually set in ini file.

### expected behaviour

Just remainder it needs to be fixed in near future. ;)

### Program version

v3.1.0 - Revision 1

### other checks

- [X] I am using the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
I think that I found the problem...

I will try to fix and recompile today (not likely)

**Comment by Haker120** [comment]
Alright. :D

**Comment by israpps** [comment]
Fixed on a98ddc1
