### ISSUE TITLE
[bug]: +OPL partion larger than 128MB causes "APA partition is broken" error

### ISSUE THREAD

**Issue by orcutt989** [israpps/HDL-Batch-installer#70]
### Issue

Originally I expanded my +OPL partition not knowing that is broken in the different launchELF utilities and saw this error.

I reformatted the entire drive (😭 ) and created a new 5GB +OPL partition , launched OPL to create the folder structure and took the hard drive out.

Then I tried loading it into HDL-Batch-Installer to reinstall my games and came accros the "APA partition is broken" error again.

It seems like it cant handle when the +OPL partition is bigger than an expected amount perhaps or am I doing this wrong?

Thanks!

**Comment by israpps** [comment]
The issue was OPL, and it was fixed a few months ago
