### ISSUE TITLE
[bug]: APA partition broken after installing ISO edited with ultraiso

### ISSUE THREAD

**Issue by gromber** [israpps/HDL-Batch-installer#72]
### Issue

I updated the aplication to latest versión, add a game before without problem, then i added a iso saved from ultraiso truncated, called DT Racer (Europe) (En,Fr,De,Es,It), the process stoped without suscess, the hdd isn´t detected, i restart pc and connect again my hdd into the usb and now i cant add more games, not tested yet with the ps2.

<img width="625" alt="Captura de pantalla 2023-12-08 211240" src="https://github.com/israpps/HDL-Batch-installer/assets/18592645/9971ca35-77a3-499d-8d71-25c75437c517">

### expected behaviour

I expected...

### other checks

- [x] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
Run hddchecker from console

Was there any error message after installation finished?

**Comment by gromber** [comment]
![Captura de pantalla 2023-12-08 214631](https://github.com/israpps/HDL-Batch-installer/assets/18592645/a4a5b931-d2d0-4607-9f8b-ab376dc0da6c)
![Captura de pantalla 2023-12-08 214602](https://github.com/israpps/HDL-Batch-installer/assets/18592645/c22665b1-9810-448e-90ba-196e4744f7cf)
![2023-12-08 21-46-11 mkv_snapshot_03 31_ 2023 12 08_21 56 15](https://github.com/israpps/HDL-Batch-installer/assets/18592645/194886c7-bdea-4659-bc9f-3303441c1bb6)

Now it is analyzing the surface of the hard drive. [https://i.imgur.com/TSQbqfe.png](url)



Before remove from pc, i checked crystaldiskinfo and was in yellow the disk :P

open ps2 loader still autoboot in the console (SoftDev2)

the disk have very few hours of use.

**Comment by gromber** [comment]
![Screenshot 2023-12-09 02-13-48](https://github.com/israpps/HDL-Batch-installer/assets/18592645/9ffc2e95-0a59-4d92-a20a-76692cb8ebd6)

After using hddchecker, hdd is detected again with hdl batch installer as ps2 hdd so i tried again to add the game and have this error, i think was the same  or similar of the first time, then software freezes and the hdd isn´t detected.

<img width="587" alt="Captura de pantalla 2023-12-09 124110" src="https://github.com/israpps/HDL-Batch-installer/assets/18592645/db5592f9-74ec-4d69-ae2b-1358928add6f">

I guess it must be a problem with my hard drive.

**Comment by gromber** [comment]
I added the hard drive to a internal pc with sata (i was using before a usb hdd case) to check problems, and now i added that game and a few more without problem... must be a personal problem.

there is also a partition of a game, that i rename and now can´t remove it in opl or uLE (silent hill 2 dc pal)

Thanks for try to help me.
