### ISSUE TITLE
[bug]: Do not scan for partitions again when closing the Create Partition menu

### ISSUE THREAD

**Issue by BerntA** [israpps/HDL-Batch-installer#75]
### Issue

Accidentally opening the create partition menu will trigger a new partition scan when you close it - even if you did not actually create a new partition.. just why?

### expected behaviour

I expected it not to do this.

### Program version

v3.5.1

### In which package have you experienced this issue?

64 bits

### other checks

- [X] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
It did? I probably left it intentionally while creating and debugging the feature.
I'll try to solve that!

**Comment by BerntA** [comment]
Yeah, it re-scans the whole hdd again regardless,
cheers! 👍

**Comment by israpps** [comment]
fixed on #76
