### ISSUE TITLE
A multi-disc game that cannot install the second disc's game content.[bug]: 

### ISSUE THREAD

**Issue by Falleninmemary** [israpps/HDL-Batch-installer#81]
### Issue

After installing the first disc, the second disc could not be installed, and the log is as follows:
![Snipaste_2024-05-26_08-26-47](https://github.com/israpps/HDL-Batch-installer/assets/24239673/11a4cd43-d9be-44ef-bbbc-af6665352fdc)

### expected behaviour

I expected...

### other checks

- [x] I tested the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)

**Comment by israpps** [comment]
This is an issue with HDL dump partition naming

Since this game shares the same game ID for both discs what you should do is make sure that the name of both files is not the same on the first 17 characters and disable database renaming.

**Comment by Falleninmemary** [comment]
> This is an issue with HDL dump partition naming
> 
> Since this game shares the same game ID for both discs what you should do is make sure that the name of both files is not the same on the first 17 characters and disable database renaming.

Okay, thank you
