### ISSUE TITLE
[FR]: Add the ability to add PS1 games

### ISSUE THREAD

**Issue by Dreamboum** [israpps/HDL-Batch-installer#94]
### Explanation

I would like you to add this option. I prefer to use the hard drive rather than the USB stick or FTP. I find it boring that we have to do all this for PS1 games. If possible, add at least one option for PS1 games in .vcd format

### fature related

- [X] game Installation
- [X] Title Database
- [X] ART Downloader
- [X] Game management
- [X] HDD management
- [X] Others...

### other checks

- [X] I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
- [X] This Feature requires an update of WxWidgets
- [X] Needs an update of [HDL Dump](https://github.com/ps2homebrew/hdl-dump)

**Comment by israpps** [comment]
Transferring PS1 games is implicitly supported via the "mount partition" and HDD file manager features.

**Comment by Dreamboum** [comment]
![popse](https://github.com/user-attachments/assets/4cc1e80b-538b-453a-9651-cf97a8c17457)

Yes, I had already found it, but I forgot to mention it to you. The problem is that when you want to add files from the partition mount, it doesn't work and there is a message that says 'insufficient space'. So there you have it.

**Comment by israpps** [comment]
please make sure you have an up to date DOKAN driver.

**Comment by Dreamboum** [comment]
> please make sure you have an up to date DOKAN driver.

[](https://github.com/dokan-dev/dokany)

I already installed the DOKAN drivers before you told me, and despite that, it still says 'insufficient space'.

**Comment by israpps** [comment]
> > please make sure you have an up to date DOKAN driver.
> 
> I already installed the DOKAN drivers before you told me, and despite that, it still says 'insufficient space'.

then i'm not sure what's going on.

at least check if there is any error on the log

**Comment by Dreamboum** [comment]
I don't have this error log, I can't find it anywhere

**Comment by israpps** [comment]
> I don't have this error log, I can't find it anywhere

its on the cmd therminal that pops in as soon as you run the program...

**Comment by Dreamboum** [comment]
```
Loading lang ID [0]
Checking for updates...
we have internet! Checking for Updates...
sucessfully recovered version tag from github
this version is the latest release!
welcome to HDL Batch Installer [v3.6.0 - Revision 1]
Standard error: Cannot open error report, read the terminal logs to find the issue
> Config File Loaded!
database mode=0
debug level=5
MiniOPL=0
OSD_Hide=0
Default_iso_path=C:\
Default DMA Mode=*u4
Custom Icon Loader=1
Report Unknown Game ID's=0
Game Title Database, 15853 ID's registered
        hdd0: 953867 MB
        hdd1: 953867 MB
        hdd2: 476937 MB, formatted Playstation 2 HDD
selected hdd2:
total: [476937]
used:  [294144]
free:  [182784]
initializing libPS2HDD...
 - accessing device '\\.\PHYSICALDRIVE2'
libPFSShell init
- I/O buffer size 65536
 - Initializing APA:
hdd: PS2 APA Driver v2.5 (c) 2003 Vector
hdd: max open = 1, 3 buffers
hdd: 11:31:50 09/09/2024
hdd: disk0: 0x3a384c40 sectors, max 0x01000000
hdd: checking log...
hdd: drive status 0, format version 00000002
hdd: version 0000 driver start.
 - Initializing PFS:
pfs Playstation Filesystem Driver v2.2
ps2fs: (c) 2003 Sjeep, Vector and Florin Sasu
pfs Max mount: 1, Max open: 1, Number of buffers: 10
pfs version 0000 driver start.
 - Initializing HDLFS:
PFSShell: finished init
PFSShell: Closing device
Obtaining partition table...
found Partition
        [__net]
found Partition
        [__system]
found Partition
        [__sysconf]
found Partition
        [__common]
found Partition
        [__boot]
found Partition
        [HDLoader Settings]
found Partition
        [+OPL]
found Partition
        [+Roms]
found Partition
        [+Saves]
found conflict
found conflict
found conflict
> Calling PFSFUSE to mount partition
        Command: [Common\pfsfuse.exe --partition=+OPL \\.\PHYSICALDRIVE2 O -o volname=+OPL]
hdd: PS2 APA Driver v2.5 (c) 2003 Vector
hdd: max open = 1, 3 buffers
hdd: 11:32:06 09/09/2024
hdd: disk0: 0x3a384c40 sectors, max 0x01000000
hdd: checking log...
hdd: drive status 0, format version 00000002
hdd: version 0000 driver start.
pfs Playstation Filesystem Driver v2.2
ps2fs: (c) 2003 Sjeep, Vector and Florin Sasu
pfs Max mount: 1, Max open: 32, Number of buffers: 127
pfs version 0000 driver start.
```

**Comment by Dreamboum** [comment]
I can't see what's blocking it.

**Comment by israpps** [comment]
how did you make this hdd format? via some premade hdd image?

**Comment by israpps** [comment]
have you tried moving those files with the hdd filebrowser?
![image](https://github.com/user-attachments/assets/607fe9e4-c2a4-49e9-8e8d-87e6486c9e8f)

**Comment by Dreamboum** [comment]
Well, I formatted the hard drive in exFAT and added the first game with WinHIIP, then with your program.

**Comment by israpps** [comment]
> Well, I formatted the hard drive in exFAT and added the first game with WinHIIP, then with your program.

winhiip is ancient software from hdloader era. it's usage is TOTALLY discouraged

**Comment by Dreamboum** [comment]
So I have to redo everything?
